language: java
jdk: openjdk8

script:
  - mvn clean install
  - mvn package

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build . -t "wermajew/fileanalyzer:latest"
  - docker images

deploy:
  provider: script
  script: docker push "wermajew/fileanalyzer:latest"
  on:
    branch: master

services:
  - docker
